<?php

/**
 * Implementiong hook_permission
 */
function form_example_permission() {
    return array(
        'submit form_example' => array(
            'title' => t('Submit form_example'),
            'description' => t('Submit the form_example form.'),
        ),
    );
}

/**
 * Implementing hook menu
 */
function form_example_menu() {
    $items = array();

    $items['form-example'] = array(
        'title' => 'My Example form',
        // Page callback, etc. need to be added here.
        'page callback' => 'drupal_get_form',
        //Passing form id as an argument
        'page arguments' => array('form_example_form'),
        'access arguments' => array('submit form_example'),
        'type' => MENU_NORMAL_ITEM,
    );
    return $items;
}

/**
 * Implementing example form
 */
function form_example_form($form, &$form_state) {

    $form['mynumber'] = array(
        '#type' => 'textfield',
        '#title' => t('My number'),
        '#size' => 10,
        '#maxlength' => 10,
        '#required' => TRUE,
        '#description' => t('Please enter a valid number.')
    );

    $form['mytextfield'] = array(
        '#type' => 'textfield',
        '#title' => t('My Textfield'),
        '#size' => 60,
        '#maxlength' => 120,
        '#required' => TRUE,
    );

    $form['mytext'] = array(
        '#type' => 'textarea',
        '#title' => t('My Textarea'),
        '#required' => TRUE,
        '#description' => t('Please enter some text.')
    );

    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => t('Add Item'),
    );

    return $form;
}

/**
 * Implemeting form validator
 */
function form_example_form_validate($form, &$form_state) {
    if (!is_numeric($form_state['values']['mynumber'])) {
        form_set_error('mynumber', t('You must enter a valid number'));
        return FALSE;
    }
    return TRUE;
}

/**
 * Implementing a submit handler
 */
function form_example_form_submit($form, &$form_state) {
    $fe_id = db_insert('form_example')
        ->fields(array(
            'mynumber' => $form_state['values']['mynumber'],
            'mytextfield' => $form_state['values']['mytextfield'],
            'mytext' => $form_state['values']['mytext'],
        ))
        ->execute();
    drupal_set_message(t('Your form entry has been saved.'));
}
