<?php

function myrender_array_menu() {
    $items['mypage-html'] = array(
        'title' => 'My page with HTML-style function',
        'page callback' => 'myrender_array_html_page',
        'access callback' => TRUE,
    );

    $items['mypage-renderable'] = array(
        'title' => 'My page with render array function',
        'page callback' => 'myrender_array_renderable_page',
        'access callback' => TRUE,
    );

    return $items;
}

/**
 * Implementing hook theme
 */
function myrender_array_theme($existing, $type, $theme, $path) {
    return array(
        'myrender_array_function' => array(
            'variables' => array('text_one' => NULL, 'text_two' => NULL),
        ),
        'myrender_array_template' => array(
            'variables' => array('text_one' => NULL, 'text_two' => NULL),
            'template' => 'myrender_array_template'
        ),
    );
}

/**
 * Callback function using HTML output
 * @return string
 */
// Previous method (still works) of generating a page by returning HTML
function myrender_array_html_page() {
    $text_one = "This is text one";
    return theme('myrender_array_function', array('text_one' => $text_one, 'text_two' => t('Text Two!')));
}

/**
 * Callback function using renderable array
 * @return array
 */
// New method of generating the render array and returning that.
function myrender_array_renderable_page() {
    $text_one = "This is text one";
    $output = array(
        '#theme' => 'myrender_array_template',
        '#type' => 'markup',
        '#text_one' => $text_one,
        '#text_two' => 'Text two',
    );
    return $output;
}

/**
 * Implementing theme function
 */
function theme_myrender_array_function($variables) {
    $output = "<h2>" . $variables['text_one'] . "</h2>";
    $output .= "<p>" . $variables['text_two'] . "</p>";

    return $output;
}
